clone:
  git:
    image: fish
    commands:
      - cd ~/.exoci
      - if test -d duckquill
      -   cd duckquill
      -   git pull
      - else
      -   git clone https://git.exozy.me/daudix/duckquill.git
      - end

pipeline:
  build:
    image: fish
    commands:
      - cd ~/.exoci/duckquill
      - zola build --output-dir /srv/http/pages/duckquill --force
